### ISSUE TITLE
backend, npm run dev errors

### ISSUE THREAD

**Issue by OpTriumph** [OpTriumph/MiniTwitter#11]
[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node app.js`
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'bcrypt'
Require stack:
- H:\Master\MiniTwitter-master\back\routes\user.js
- H:\Master\MiniTwitter-master\back\app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)    
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (H:\Master\MiniTwitter-master\back\routes\user.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'H:\\Master\\MiniTwitter-master\\back\\routes\\user.js',
    'H:\\Master\\MiniTwitter-master\\back\\app.js'
  ]
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by OpTriumph** [comment]
I first solved this error by delete the duplicate `const cors = require("cors");` 
[nodemon] restarting due to changes...
[nodemon] starting `node app.js`
H:\Master\MiniTwitter-master\back\app.js:10
const cors = require("cors");
      ^

SyntaxError: Identifier 'cors' has already been declared
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)    
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
[nodemon] app crashed - waiting for file changes before starting...

After this, the error on top occurs

**Comment by L-SuMin** [comment]
To fix the first one, install bycrpt.
**`npm install bycrpt`**  in the back folder.

**Comment by OpTriumph** [comment]
is this another package problem?
If your backend server is working, can you paste your package.json here?
thank you

**Comment by L-SuMin** [comment]
Ah... That one is not a package problem.
_back\model\hashtag.js_ file has called in _back\model\index.js_, but hashtag.js does not exist.
Maybe, JeongJuRy deleted hashtag and image in the last commit in #8 and he forgot to change some codes

**Comment by JeongJuRyu** [comment]
죄송합니다 ㅠㅠ bcrypt 라이브러리 추가해놓고 정작 설치를 안 했네요
그런데 혹시 hashtag 호출 코드는 제가 잘 지웠는데 왜 오류가 뜰까요??
